name: BurgerSellWands
main: Heisenburger69\BurgerSellWands\Main
version: 1.0.0
api: 3.0.0
author: Heisenburger69
description: Plugin implements fully customizable BurgerSellWands for PMMP
depend: ["EconomyAPI"]

commands:
 sellwand:
  description: "Give sell wands to a player"
  aliases: ["sw", "burgersellwand"]
  permission: sellwand.command

permissions:
  sellwand.command:
   default: op
   description: "Allows the use of /sellwand"
  sellwand.use:
   default: true
   description: "Allows player use Sell Wands on Chests"